# Generated by Django 4.1.2 on 2022-10-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_record_tags_alter_record_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
    ]
