# Generated by Django 4.1.2 on 2022-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_user_id_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
