# Generated by Django 4.1.2 on 2022-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_record_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=2),
            preserve_default=False,
        ),
    ]
