name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove docker.io -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Wait for Docker to start
        run: |
          while [ ! -S /var/run/docker.sock ]; do
            sleep 1
          done

      - name: Build and deploy
        run: |
          cd /home/user/records/
          docker-compose down
          docker-compose up -d
